include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Adjust the severity of these lints if necessary
    avoid_print: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore

linter:
  rules:
    # Add or modify rules to match your requirements
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_use_package_imports: true
    avoid_unnecessary_containers: true
    prefer_const_constructors_in_immutables: true
    use_key_in_widget_constructors: true
    avoid_returning_null_for_void: true
