name: CI/CD for Flutter Web

on:
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test test/widget_test.dart

      - name: Build web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        if: success()  # Only deploy if previous steps were successful
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: your-custom-domain.com  # Optional: Add custom domain if needed
